CREATE TABLE IF NOT EXISTS YAMAHA_USER(ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(255) NOT NULL,EMAIL VARCHAR(255) NOT NULL,MOBILE_NO VARCHAR(200) NOT NULL,ADDRESS_LINE1 VARCHAR(255),ADDRESS_LINE2 VARCHAR(255),STATE VARCHAR(255),CREATED_ON DATE NOT NULL,CREATED_BY VARCHAR(255) NOT NULL,MODIFIED_ON DATE NOT NULL,MODIFIED_BY VARCHAR(255) NOT NULL)

CREATE TABLE IF NOT EXISTS PRODUCT(ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), PRICE VARCHAR(255), CREATED_ON DATE NOT NULL,CREATED_BY VARCHAR(255) NOT NULL,MODIFIED_ON DATE NOT NULL,MODIFIED_BY VARCHAR(255) NOT NULL)

CREATE TABLE IF NOT EXISTS IMAGE(ID INT AUTO_INCREMENT PRIMARY KEY, PRODUCT_ID INT, IMAGE VARCHAR(255), CREATED_ON DATE NOT NULL,CREATED_BY VARCHAR(255) NOT NULL,MODIFIED_ON DATE NOT NULL,MODIFIED_BY VARCHAR(255) NOT NULL)

CREATE TABLE IF NOT EXISTS ENQUIRY(ID INT AUTO_INCREMENT PRIMARY KEY, CUST_ID INT, PRODUCT_ID INT, QUANTITY INT, CREATED_ON DATE NOT NULL,CREATED_BY VARCHAR(255) NOT NULL,MODIFIED_ON DATE NOT NULL,MODIFIED_BY VARCHAR(255) NOT NULL)

